### ISSUE TITLE
Submission improovments

### ISSUE THREAD

**Issue by ricco386** [vault19/django-courses#26]
Submission button should not be visible on all lectures

A submitted submission form (non editable) should be visible on the lecture detail right away

A submitted submission form (editable) should indicate that the user is editing an already submitted form

**Comment by ricco386** [comment]
Updated DB model to have `required_submission` in both lecture and chapter.

Added new option `Disabled` for both. If `required_submission` is disabled user is not able to access the submission page, and all button to submissions are hidden.

**Comment by ricco386** [comment]
When visiting the submission page there is `#submission-form` appended in the url. Browser should scroll to the html id, which is the submission form id.

Second alternative is to have submission form on the top above the lecture (or course) content, or to have just the form (which I think is the worst alternative since student can not return back to material about which he is writing submission...

**Comment by marekmansell** [comment]
**Submission form visibility**

I personally think that the submission form should be shown in one of the following ways:

- either the form is shown right away at the bottom of the page (beneath the lecture description)
- or after clicking the "Submit" button a Modal opens with the Submission form.

The current way of adding the submission form to the existing page after clicking the button might be confusing for users - the same page sometimes has a submission form and sometimes does not...

I prefer the first option (showing the form right away and always).

---

**Indicating that a submission has already been submitted**

Currently, once a user submits his or hers work and re-opens the submission form, the previously submitted data are pre-filled (which is good) bud there is no way of knowing that the form has been successfully submitted and stored in the server database. Hence, the users might get confused and re-submit the form several times.

One way to solve this issue would be to show the filled out form whenever the user returns to a lecture with a submitted submission, but make it **read only**. Only after hitting a "Update submission" button would the form fields become editable.

**Comment by ricco386** [comment]
My last commit should resolve all the problems in submissions (at least for lectures).
